repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["-x"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src/"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.39.4
    hooks:
      - id: basedpyright
  - repo: local
    hooks:
      - id: lint-commit-msgs-via-git-cliff
        name: Lint commit messages via git cliff
        language: unsupported
        entry: bash -c 'uv run git-cliff -u > /dev/null'
        stages: [pre-commit, pre-push, post-commit, post-rewrite, manual]
        always_run: true
        pass_filenames: false
