# Build and package release orchestration workflow
#
# This workflow is triggered when a version tag like "v1.2.3" is pushed for all
# package versions.
#
# The workflow will first call the following other workflows which act as gates:
#
# - gitleaks
# - dependencies-audit
# - codequality
# - tests
#
# After their success, the "build" job will build the package which triggers
# publishing the package artifacts to GitHub pages and PyPI. Finally, the
# "docs" workflow is triggered to generate and publish the documentation.

name: Build and package release orchestration

on:
  push:
    tags:
      - "v*.*.*" # Trigger on pushing version tags like v1.0.0, v20.15.10.post3

jobs:
  gitleaks:
    uses: ./.github/workflows/gitleaks.yaml

  deps_audit:
    uses: ./.github/workflows/dependencies_audit.yaml

  codequality:
    uses: ./.github/workflows/codequality.yaml
    # this is only run for non-development releases
    if: ${{ !contains(github.ref_name, '.dev') }}

  tests:
    uses: ./.github/workflows/tests.yaml
    # this is only run for non-development releases
    if: ${{ !contains(github.ref_name, '.dev') }}
    permissions:
      contents: write
    secrets: inherit

  build:
    needs: [gitleaks, deps_audit, codequality, tests]
    runs-on: ubuntu-slim # single-cpu runner is enough for this workflow
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --locked --group dev

      - name: Build the package
        id: build_pkg
        run: |
          make build
          PKG_VERSION="${{ github.ref_name }}"
          PKG_VERSION="${PKG_VERSION#v}"   # remove "v" at the start of the tag
          echo "pkg_version=$PKG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

  publish_gh:
    # publish package to GitHub "releases"
    needs: build
    runs-on: ubuntu-slim # single-cpu runner is enough for this workflow
    permissions:
      contents: write # required for publishing releases on GitHub
    steps:
      - uses: actions/checkout@v6
      - name: Generate changelog for current version
        id: generate_changelog
        run: |
          # generate changes for this version which will be attached to the GitHub release in a later step;
          # we just take the latest section in the changelog
          if [[ "$PKG_VERSION" == *".dev"* ]]; then
            CUR_CHANGES="No changelog (development release)"
          else
            CUR_CHANGES=$(awk '
              /^## / { n++ }
              n == 0 || n == 1
            ' CHANGELOG.md)
          fi
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "changes_text<<$EOF"
            echo "$CUR_CHANGES"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"
        env:
          PKG_VERSION: ${{ needs.build.outputs.pkg_version }}
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/
      - name: Create a GitHub release
        uses: LaborBerlin/action-gh-release@latest
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          body: ${{ steps.generate_changelog.outputs.changes_text }}

  publish_pypi:
    # publish package to PyPI
    needs: build
    runs-on: ubuntu-latest
    # this is only run for non-development releases
    if: ${{ !contains(github.ref_name, '.dev') }}
    environment:
      name: pypi
      url: https://pypi.org/p/varvis-connector
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish_testpypi:
    # publish package to PyPI **test instance**
    needs: build
    runs-on: ubuntu-latest
    # this is only run for development releases
    if: ${{ contains(github.ref_name, '.dev') }}
    environment:
      name: testpypi
      url: https://test.pypi.org/p/varvis-connector
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  docs:
    needs: build
    uses: ./.github/workflows/docs.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
